language: ruby
rvm:
  - 2.3.1
addons:
  code_climate:
    repo_token:
      secure: fssr5/Z89S5l7gZl5Xv1Zw/sbmAN/IUSaved5D4rz6qVNbYtlJb3cXnGTEIWrLl7tIOCYTmKo7KSp3PDwffEIR2r4COBEAmeyi6Vg/Rgg6fUWfx+QIQdIgGd6v42jBnGxUDTV8CBCjkV1VrQ2IK+JYBS019kA8SsiUf0cIUdF1oxY8xvEo6yU0kPNbrL+GrAL6J/xIqHo6Vrdc3I7afn4GurSOU8+JDPXMOX6BsnrUbvL1ufHkYjnmXqCloD1c2+ek1cIumYPX2BD89a06fRU4qe0DMsOYA/HL60rS+D6D2J+OyfbNVIeLlvxSa/ldXfrOBOqf76n/4IeG17+7KtEWByKdZGS51imdMZKfhUGZBtpK1QVlKNaCBt9Pb35uVFn+zf07zRpHudQSBgjef5vZZahvO6yW9zVVCCICTRCCHzo4NsrMl4w/ON8VoK42KPkrFfxOHBRTsT+JavNa16FFYWKLajvWri60jJRCOAXBxDhvMggQPIoM9H+RBjccDRnw8cx4zs8VLyD17MmN+/AYi4NfE+wyKjP8CVCyc3AVO4bRE9jOHD34SpE/vAAcQY7SqkxIpkLRaLGEg8O5yWqIyCuTEZRZTJwuDey3iMMTo5CGaCEAptkM8MtUo7MlYX75DHYx9ZSB7mlhpSpLCFY6vyxJxoaefDuv2ORaw+H40=
install:
  - bundle install --jobs=3 --retry=3 --deployment
- bundle exec rake db:migrate RAILS_ENV=test
after_script:
  - bundle exec codeclimate-test-reporter
deploy:
  app: radiologia
  provider: heroku
  api_key:
    secure: wXezHblVRUyCMOfIf3RKS24LdxxY5Oq1N9EogY98tqrKbgtOuyHtTtASrfCRlMXQ8ZhUzUtAixh9p/uua7YJsaQ9hOymXj+3PE4UnlwNJ7MT64uj89vAZwoW4NReCeWAlvqJNh19KMXkn/kWmPr+/4QAv6tRTZbDGmsJ4DK6wgMP6icS/Nr/6lL9NCRsKfWrIdKsU3Lyqo5/qATI9nsC9K4nNf1xTd4GghcHvuGmNjkjHN6SVG/gTJsdgbj2KDmF4eZgN010tEGxYEfWiIQLp6MJVLpAoG1gdpG1JS7K98Y5E5ofvUEpjuybn63zioVt9uFdYvD0MzuFEeKBQPD9Hv+ix2Igx79GYyngf+KDNqM5kLlfdSlACRgqrFKffOtEz73xO5ImgEHDSkz0+48oexZUEWc9nrBHiWv3Q4BefjV4q57IhnbzvkqogpEBVPoycXb6eWi3opEeoTUXTO3/3lMM9q8f3/MUd8crv2BxryqlM2KvkYAWgWGA8H3Or8674UT4osmztf3GavtMHCNUnPkvkay01S5tza6H/JNs40d3f1Gbv3kv13cC7YjFLoOy06bfqzPqYkYF/zSvkxQesNHI5cDzSAU1x7wnRvCfsvguwmMAQz5NGXMhr85TXF23qfMNzdK7NK0ry5BH7hJcJRyQhChnDiF2Jxnv/wBJKrE=
  skip_cleanup: false
  run:
    - "rake db:migrate"
    - "restart"
