language: ruby
rvm:
- 2.2.0
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec rake db:migrate
  - bundle exec rake spec
deploy:
  app: radiologia
  provider: heroku
  api_key:
    secure: wXezHblVRUyCMOfIf3RKS24LdxxY5Oq1N9EogY98tqrKbgtOuyHtTtASrfCRlMXQ8ZhUzUtAixh9p/uua7YJsaQ9hOymXj+3PE4UnlwNJ7MT64uj89vAZwoW4NReCeWAlvqJNh19KMXkn/kWmPr+/4QAv6tRTZbDGmsJ4DK6wgMP6icS/Nr/6lL9NCRsKfWrIdKsU3Lyqo5/qATI9nsC9K4nNf1xTd4GghcHvuGmNjkjHN6SVG/gTJsdgbj2KDmF4eZgN010tEGxYEfWiIQLp6MJVLpAoG1gdpG1JS7K98Y5E5ofvUEpjuybn63zioVt9uFdYvD0MzuFEeKBQPD9Hv+ix2Igx79GYyngf+KDNqM5kLlfdSlACRgqrFKffOtEz73xO5ImgEHDSkz0+48oexZUEWc9nrBHiWv3Q4BefjV4q57IhnbzvkqogpEBVPoycXb6eWi3opEeoTUXTO3/3lMM9q8f3/MUd8crv2BxryqlM2KvkYAWgWGA8H3Or8674UT4osmztf3GavtMHCNUnPkvkay01S5tza6H/JNs40d3f1Gbv3kv13cC7YjFLoOy06bfqzPqYkYF/zSvkxQesNHI5cDzSAU1x7wnRvCfsvguwmMAQz5NGXMhr85TXF23qfMNzdK7NK0ry5BH7hJcJRyQhChnDiF2Jxnv/wBJKrE=
